/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DisplayCardTheme } from "./components/display-card/display-card";
import { PlatformType } from "./utils/platform";
export namespace Components {
    interface DisplayCard {
        "images": string;
        "linkTo": string;
        "theme": DisplayCardTheme;
    }
    interface NavBar {
        "authenticated": boolean;
        "platform": PlatformType;
        "showMultiplier": number;
    }
    interface StickyScroller {
        "bottom": boolean;
        "endOffset": number;
        "startOffset": number;
    }
}
declare global {
    interface HTMLDisplayCardElement extends Components.DisplayCard, HTMLStencilElement {
    }
    var HTMLDisplayCardElement: {
        prototype: HTMLDisplayCardElement;
        new (): HTMLDisplayCardElement;
    };
    interface HTMLNavBarElement extends Components.NavBar, HTMLStencilElement {
    }
    var HTMLNavBarElement: {
        prototype: HTMLNavBarElement;
        new (): HTMLNavBarElement;
    };
    interface HTMLStickyScrollerElement extends Components.StickyScroller, HTMLStencilElement {
    }
    var HTMLStickyScrollerElement: {
        prototype: HTMLStickyScrollerElement;
        new (): HTMLStickyScrollerElement;
    };
    interface HTMLElementTagNameMap {
        "display-card": HTMLDisplayCardElement;
        "nav-bar": HTMLNavBarElement;
        "sticky-scroller": HTMLStickyScrollerElement;
    }
}
declare namespace LocalJSX {
    interface DisplayCard {
        "images"?: string;
        "linkTo"?: string;
        "theme"?: DisplayCardTheme;
    }
    interface NavBar {
        "authenticated"?: boolean;
        "platform"?: PlatformType;
        "showMultiplier"?: number;
    }
    interface StickyScroller {
        "bottom"?: boolean;
        "endOffset"?: number;
        "startOffset"?: number;
    }
    interface IntrinsicElements {
        "display-card": DisplayCard;
        "nav-bar": NavBar;
        "sticky-scroller": StickyScroller;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "display-card": LocalJSX.DisplayCard & JSXBase.HTMLAttributes<HTMLDisplayCardElement>;
            "nav-bar": LocalJSX.NavBar & JSXBase.HTMLAttributes<HTMLNavBarElement>;
            "sticky-scroller": LocalJSX.StickyScroller & JSXBase.HTMLAttributes<HTMLStickyScrollerElement>;
        }
    }
}
