/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Theme } from "./utils/theme";
import { DisplayCardType } from "./components/display-card/display-card";
import { PlatformType } from "./utils/platform";
import { InputType } from "./components/simple-input/simple-input";
export namespace Components {
    interface DisplayCard {
        "bottomSubtitleName": string;
        "bottomTitleName": string;
        "cardType": DisplayCardType;
        "images": string;
        "linkTo": string;
        "theme": Theme;
    }
    interface EnquireModal {
        "postTitle": string;
        "previewImage": string;
    }
    interface FooterNav {
    }
    interface ImageGallery {
        "images": string;
        "photographer": string;
        "postExcerpt": string;
        "postTitle": string;
        "previewImage": string;
    }
    interface ImageGalleryLink {
        "imageIndex": number;
    }
    interface NavBar {
        "authenticated": boolean;
        "platform": PlatformType;
        "showMultiplier": number;
    }
    interface SimpleButton {
        "disabled": boolean;
        "fillWidth": boolean;
        "theme": Theme;
    }
    interface SimpleInput {
        "name": string;
        "placeholder": string;
        "required": boolean;
        "type": InputType;
        "value": string;
    }
    interface StickyScroller {
        "bottom": boolean;
        "endOffset": number;
        "startOffset": number;
    }
    interface TelePortal {
    }
}
declare global {
    interface HTMLDisplayCardElement extends Components.DisplayCard, HTMLStencilElement {
    }
    var HTMLDisplayCardElement: {
        prototype: HTMLDisplayCardElement;
        new (): HTMLDisplayCardElement;
    };
    interface HTMLEnquireModalElement extends Components.EnquireModal, HTMLStencilElement {
    }
    var HTMLEnquireModalElement: {
        prototype: HTMLEnquireModalElement;
        new (): HTMLEnquireModalElement;
    };
    interface HTMLFooterNavElement extends Components.FooterNav, HTMLStencilElement {
    }
    var HTMLFooterNavElement: {
        prototype: HTMLFooterNavElement;
        new (): HTMLFooterNavElement;
    };
    interface HTMLImageGalleryElement extends Components.ImageGallery, HTMLStencilElement {
    }
    var HTMLImageGalleryElement: {
        prototype: HTMLImageGalleryElement;
        new (): HTMLImageGalleryElement;
    };
    interface HTMLImageGalleryLinkElement extends Components.ImageGalleryLink, HTMLStencilElement {
    }
    var HTMLImageGalleryLinkElement: {
        prototype: HTMLImageGalleryLinkElement;
        new (): HTMLImageGalleryLinkElement;
    };
    interface HTMLNavBarElement extends Components.NavBar, HTMLStencilElement {
    }
    var HTMLNavBarElement: {
        prototype: HTMLNavBarElement;
        new (): HTMLNavBarElement;
    };
    interface HTMLSimpleButtonElement extends Components.SimpleButton, HTMLStencilElement {
    }
    var HTMLSimpleButtonElement: {
        prototype: HTMLSimpleButtonElement;
        new (): HTMLSimpleButtonElement;
    };
    interface HTMLSimpleInputElement extends Components.SimpleInput, HTMLStencilElement {
    }
    var HTMLSimpleInputElement: {
        prototype: HTMLSimpleInputElement;
        new (): HTMLSimpleInputElement;
    };
    interface HTMLStickyScrollerElement extends Components.StickyScroller, HTMLStencilElement {
    }
    var HTMLStickyScrollerElement: {
        prototype: HTMLStickyScrollerElement;
        new (): HTMLStickyScrollerElement;
    };
    interface HTMLTelePortalElement extends Components.TelePortal, HTMLStencilElement {
    }
    var HTMLTelePortalElement: {
        prototype: HTMLTelePortalElement;
        new (): HTMLTelePortalElement;
    };
    interface HTMLElementTagNameMap {
        "display-card": HTMLDisplayCardElement;
        "enquire-modal": HTMLEnquireModalElement;
        "footer-nav": HTMLFooterNavElement;
        "image-gallery": HTMLImageGalleryElement;
        "image-gallery-link": HTMLImageGalleryLinkElement;
        "nav-bar": HTMLNavBarElement;
        "simple-button": HTMLSimpleButtonElement;
        "simple-input": HTMLSimpleInputElement;
        "sticky-scroller": HTMLStickyScrollerElement;
        "tele-portal": HTMLTelePortalElement;
    }
}
declare namespace LocalJSX {
    interface DisplayCard {
        "bottomSubtitleName"?: string;
        "bottomTitleName"?: string;
        "cardType"?: DisplayCardType;
        "images"?: string;
        "linkTo"?: string;
        "theme"?: Theme;
    }
    interface EnquireModal {
        "postTitle"?: string;
        "previewImage"?: string;
    }
    interface FooterNav {
    }
    interface ImageGallery {
        "images"?: string;
        "photographer"?: string;
        "postExcerpt"?: string;
        "postTitle"?: string;
        "previewImage"?: string;
    }
    interface ImageGalleryLink {
        "imageIndex"?: number;
        "onOpenImageGallery"?: (event: CustomEvent<number>) => void;
    }
    interface NavBar {
        "authenticated"?: boolean;
        "platform"?: PlatformType;
        "showMultiplier"?: number;
    }
    interface SimpleButton {
        "disabled"?: boolean;
        "fillWidth"?: boolean;
        "theme"?: Theme;
    }
    interface SimpleInput {
        "name"?: string;
        "onValueChanged"?: (event: CustomEvent<string>) => void;
        "placeholder"?: string;
        "required"?: boolean;
        "type"?: InputType;
        "value"?: string;
    }
    interface StickyScroller {
        "bottom"?: boolean;
        "endOffset"?: number;
        "startOffset"?: number;
    }
    interface TelePortal {
    }
    interface IntrinsicElements {
        "display-card": DisplayCard;
        "enquire-modal": EnquireModal;
        "footer-nav": FooterNav;
        "image-gallery": ImageGallery;
        "image-gallery-link": ImageGalleryLink;
        "nav-bar": NavBar;
        "simple-button": SimpleButton;
        "simple-input": SimpleInput;
        "sticky-scroller": StickyScroller;
        "tele-portal": TelePortal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "display-card": LocalJSX.DisplayCard & JSXBase.HTMLAttributes<HTMLDisplayCardElement>;
            "enquire-modal": LocalJSX.EnquireModal & JSXBase.HTMLAttributes<HTMLEnquireModalElement>;
            "footer-nav": LocalJSX.FooterNav & JSXBase.HTMLAttributes<HTMLFooterNavElement>;
            "image-gallery": LocalJSX.ImageGallery & JSXBase.HTMLAttributes<HTMLImageGalleryElement>;
            "image-gallery-link": LocalJSX.ImageGalleryLink & JSXBase.HTMLAttributes<HTMLImageGalleryLinkElement>;
            "nav-bar": LocalJSX.NavBar & JSXBase.HTMLAttributes<HTMLNavBarElement>;
            "simple-button": LocalJSX.SimpleButton & JSXBase.HTMLAttributes<HTMLSimpleButtonElement>;
            "simple-input": LocalJSX.SimpleInput & JSXBase.HTMLAttributes<HTMLSimpleInputElement>;
            "sticky-scroller": LocalJSX.StickyScroller & JSXBase.HTMLAttributes<HTMLStickyScrollerElement>;
            "tele-portal": LocalJSX.TelePortal & JSXBase.HTMLAttributes<HTMLTelePortalElement>;
        }
    }
}
